[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200

lib_ldf_mode = deep+

build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DBACDL_BIP=1
    -DMAX_APDU=1476
    -DBACNET_PROPERTY_LISTS=1
    
    ; Regime sec
    -DMAX_TSM_TRANSACTIONS=2
    -DMAX_ADDRESS_CACHE=2
    -DMAX_COV_SUBSCRIBERS=0
    -DMAX_TREND_LOGS=0
    -DMAX_SCHEDULES=0
    -DMAX_CALENDARS=0
    -DMAX_TIME_VALUES=0
    -DMAX_ANALOG_VALUES=4
    -DMAX_BINARY_VALUES=4
    -DMAX_OBJECTS=10
    
    ; Chemins infaillibles pour main.cpp
    -I "$PROJECT_DIR/lib"
    -I "$PROJECT_DIR/lib/bacnet"

lib_deps =
    emelianov/modbus-esp8266 @ ^4.1.0
    bacnet